language: go
go:
- 1.8
before_deploy:
- make release
- tar cvfz binaries.tar.gz bin/* -C bin .
deploy:
  provider: releases
  api_key:
    secure: hTK93yyzTCKDEHBffHwt1UlDzxujfFjX2chHco6t6k/JTtwL2+kIF0gl0X4ROwp7ICoHxWpW5TQofC+RrO8ZfIXGbqeTQpKZw3lbXCdwsVA8fliUntdrdVBQT4qSfwPeeBsgiXH6LTuF+9n1vDHvG85Vvp5USXudLuM8E5ai+ol/dzVvCzEchNJTehFMJpteVgBK8vkKaPP1fgZ3bJPcbDVTsnoGaz7d+o4awkaomYasB+6SR7i7O/SO++pqNj0am1BmsWtO71ihEY08CKe4gE0Q9My6aSuKIvjnogrrxEQLz/e/1NGe4xNdcW9knkudi+UAhECtnh9R7d3zpDxpKXu3ECPZOGiZLBNPET2kSSGYNBsZQ3164h4ZKkReBRlJSTYEw3IsTQup0er64xIpmLJddJ1qGYbAyNrS/X0cKQ5lxLoSEf7H7wAAbhKq+kIQFo2vMELYZCB6nFYcxnF2fnRgVCEZArSwr7DzQasWqk6pPVIL6TGvPWIZAt2Iv93zqGyEjvULlJWf9khCFLw//bRTWR+BQ/B6tqMKPDbl9KPCr92nBM62gf5yirW7wmZKQ02rDcucbxdoWz8Bl9SREI83vnKS1F4AiyU9knCvxI37bWnMR7bVHhmalPQ7+wWifHfc+CBCxLhrdsxrvEqztORhUBrsuLfpL+4Yrp0D/G4=
  file: binaries.tar.gz
  on:
    tags: true
